### ISSUE TITLE
Detect the need for or use of the Worker & K/V updates

### ISSUE THREAD

**Issue by BigBlueHat** [WileyLabs/web-redirects-cli#15]
Free accounts only support 3 Page Rules, so we "fallback" to the `redir` Worker. Right now, most of that experience is manual...especially for later (post-creation) updates. Commands like `show` are frightening because they don't look at the Worker K/V or even state that the Worker is installed.

Additionally, with Worker's new "Custom Domain" feature, that could/should be used which would help provide a simpler mapping between those worlds (hopefully).

**Comment by alunwcom** [comment]
won't fix
